### ISSUE TITLE
TypeError: 'generator' object is not subscriptable

### ISSUE THREAD

**Issue by nguyenhoamy1602** [hyperopt/hyperopt-sklearn#100] opened 2018-05-08 13:21 UTC
When running Iris Example and MNIST Example. The following error is seen:
```
Traceback (most recent call last):
  File "1.py", line 31, in <module>
    estim.fit( X_train, y_train )
  File "/Users/nguyen.hoamy/PycharmProjects/ML/hyperopt-sklearn/hpsklearn/estimator.py", line 747, in fit
    fit_iter.send(increment)
  File "/Users/nguyen.hoamy/PycharmProjects/ML/hyperopt-sklearn/hpsklearn/estimator.py", line 657, in fit_iter
    return_argmin=False, # -- in case no success so far
  File "/Users/nguyen.hoamy/PycharmProjects/ML/venv/lib/python3.6/site-packages/hyperopt/fmin.py", line 307, in fmin
    return_argmin=return_argmin,
  File "/Users/nguyen.hoamy/PycharmProjects/ML/venv/lib/python3.6/site-packages/hyperopt/base.py", line 635, in fmin
    return_argmin=return_argmin)
  File "/Users/nguyen.hoamy/PycharmProjects/ML/venv/lib/python3.6/site-packages/hyperopt/fmin.py", line 314, in fmin
    pass_expr_memo_ctrl=pass_expr_memo_ctrl)
  File "/Users/nguyen.hoamy/PycharmProjects/ML/venv/lib/python3.6/site-packages/hyperopt/base.py", line 786, in __init__
    pyll.toposort(self.expr)
  File "/Users/nguyen.hoamy/PycharmProjects/ML/venv/lib/python3.6/site-packages/hyperopt/pyll/base.py", line 715, in toposort
    assert order[-1] == expr
TypeError: 'generator' object is not subscriptable
```

**Comment by bjkomer** [comment] 2018-05-08 15:29
This is due to an older version of `hyperopt` not working with the latest `networkx`.

You can either upgrade to the latest master of hyperopt using `pip install --upgrade git+git://github.com/hyperopt/hyperopt.git` 
or downgrade the networkx dependency using `pip install networkx==1.11`

Duplicate of #90 and hyperopt issue [325](https://github.com/hyperopt/hyperopt/issues/325)

**Closed by bjkomer** 2018-05-08 15:29 UTC
