### ISSUE TITLE
TypeError: 'generator' object has no attribute '__getitem__'  when estim.fit(X_train,y_train) please help 

### ISSUE THREAD

**Issue by david2588e** [hyperopt/hyperopt-sklearn#98] opened 2018-04-04 11:27 UTC
estim.fit( X_train, y_train )
Traceback (most recent call last):

  File "<ipython-input-10-8ecb54c50078>", line 1, in <module>
    estim.fit( X_train, y_train )

  File "C:\Users\Liu\Anaconda2\lib\site-packages\hpsklearn\estimator.py", line 746, in fit
    fit_iter.send(increment)

  File "C:\Users\Liu\Anaconda2\lib\site-packages\hpsklearn\estimator.py", line 657, in fit_iter
    return_argmin=False, # -- in case no success so far

  File "C:\Users\Liu\Anaconda2\lib\site-packages\hyperopt\fmin.py", line 307, in fmin
    return_argmin=return_argmin,

  File "C:\Users\Liu\Anaconda2\lib\site-packages\hyperopt\base.py", line 635, in fmin
    return_argmin=return_argmin)

  File "C:\Users\Liu\Anaconda2\lib\site-packages\hyperopt\fmin.py", line 314, in fmin
    pass_expr_memo_ctrl=pass_expr_memo_ctrl)

  File "C:\Users\Liu\Anaconda2\lib\site-packages\hyperopt\base.py", line 786, in __init__
    pyll.toposort(self.expr)

  File "C:\Users\Liu\Anaconda2\lib\site-packages\hyperopt\pyll\base.py", line 715, in toposort
    assert order[-1] == expr

TypeError: 'generator' object has no attribute '__getitem__'

**Comment by bjkomer** [comment] 2018-04-05 15:18
That's due to using an older version of `hyperopt` that isn't compatible with the newest `networkx`

Either install `hyperopt` from master, or downgrade `networkx` with `pip install networkx==1.11`

Duplicate of [this issue](https://github.com/hyperopt/hyperopt/issues/326)

**Closed by bjkomer** 2018-04-05 15:18 UTC
